version: "3"

services:
  app:
    build: ./klee
    volumes:
      - ./benchmarks_cache:/home/klee/benchmarks_cache
      - ./benchmarks_original:/home/klee/benchmarks_original
      - ./litmus:/home/klee/litmus
      - ./workspace:/home/klee/workspace
    tty: true
